sudo: required
services:
  - docker

before_install:
  - docker build -t nvisible29/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nvisible29/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Frontend-dev-2"
  bucket_name: "elasticbeanstalk-us-east-1-841239762339"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "AWS_ACCESS_SECRET"